import type { DesignPattern } from "@/lib/ai/design-patterns/types";

/** Services patterns (12). */
export const SERVICES_PATTERNS: DesignPattern[] = [
  {
    id: "services.large_cards",
    category: "services",
    name: "Large Cards",
    industryAffinity: ["contractor", "landscaping", "local_service", "general", "salon"],
    brandAffinity: ["modern", "approachable", "trustworthy", "premium"],
    tone: ["modern", "approachable", "trustworthy"],
    purpose: ["explain_offer"],
    requiredAssets: ["none"],
    requiredContent: ["services"],
    strengths: ["Scannable offers", "Room for short descriptions"],
    avoidWhen: ["too_many_services"],
    compatiblePatterns: [
      "hero.contractor_left",
      "hero.coastal_service",
      "hero.local_banner",
      "trust.google_reviews",
      "trust.stats_bar",
      "cta.request_quote",
      "gallery.grid",
    ],
    layoutInstructions: ["2–3 column cards", "icon or photo optional", "equal card height"],
    conversionStrength: 0.72,
    visualWeight: 0.6,
  },
  {
    id: "services.alternating",
    category: "services",
    name: "Alternating",
    industryAffinity: ["portfolio", "landscaping", "salon", "professional_services"],
    brandAffinity: ["editorial", "premium", "handcrafted", "modern"],
    tone: ["editorial", "premium", "handcrafted"],
    purpose: ["explain_offer", "show_work"],
    requiredAssets: ["project_photos"],
    requiredContent: ["services"],
    strengths: ["Story rhythm", "Pairs image with offer"],
    avoidWhen: ["few_photos"],
    compatiblePatterns: [
      "hero.editorial_split",
      "hero.asymmetric_craft",
      "trust.team_trust",
      "gallery.alternating",
      "cta.project_inquiry",
      "cta.book_consultation",
    ],
    layoutInstructions: ["zigzag image/text", "one service per band", "consistent cadence"],
    conversionStrength: 0.68,
    visualWeight: 0.7,
  },
  {
    id: "services.icon_grid",
    category: "services",
    name: "Icon Grid",
    industryAffinity: ["professional_services", "local_service", "general", "retail"],
    brandAffinity: ["modern", "minimalist", "approachable", "trustworthy"],
    tone: ["modern", "minimalist", "approachable"],
    purpose: ["explain_offer"],
    requiredAssets: ["none"],
    requiredContent: ["services"],
    strengths: ["Fast scanning", "Light visual load", "Mobile friendly"],
    avoidWhen: ["luxury_photo_brand"],
    compatiblePatterns: [
      "hero.floating_card",
      "hero.soft_gradient_service",
      "hero.trust_first_hero",
      "trust.certifications",
      "cta.schedule_visit",
      "cta.book_consultation",
    ],
    layoutInstructions: ["icon + label + one line", "3–4 columns", "tight but airy"],
    conversionStrength: 0.64,
    visualWeight: 0.45,
  },
  {
    id: "services.process_cards",
    category: "services",
    name: "Process Cards",
    industryAffinity: ["contractor", "landscaping", "professional_services", "local_service"],
    brandAffinity: ["trustworthy", "modern", "approachable", "handcrafted"],
    tone: ["trustworthy", "modern"],
    purpose: ["explain_offer", "build_trust"],
    requiredAssets: ["none"],
    requiredContent: ["process_steps", "services"],
    strengths: ["Demystifies the job", "Supports complex services"],
    avoidWhen: ["simple_impulse_offer"],
    compatiblePatterns: [
      "hero.process_hero",
      "hero.before_after_hero",
      "trust.guarantee",
      "trust.before_after",
      "cta.estimate",
      "cta.request_quote",
      "gallery.timeline",
    ],
    layoutInstructions: ["numbered cards", "3–5 steps", "CTA after last step"],
    conversionStrength: 0.8,
    visualWeight: 0.58,
  },
  {
    id: "services.timeline",
    category: "services",
    name: "Timeline",
    industryAffinity: ["contractor", "professional_services", "landscaping"],
    brandAffinity: ["timeless", "trustworthy", "modern", "minimalist"],
    tone: ["timeless", "trustworthy", "modern"],
    purpose: ["explain_offer", "build_trust"],
    requiredAssets: ["none"],
    requiredContent: ["process_steps"],
    strengths: ["Sequential clarity", "Feels organized"],
    avoidWhen: ["non_linear_offer"],
    compatiblePatterns: [
      "hero.process_hero",
      "trust.certifications",
      "gallery.timeline",
      "cta.book_consultation",
    ],
    layoutInstructions: ["vertical or horizontal timeline", "milestones labeled"],
    conversionStrength: 0.7,
    visualWeight: 0.52,
  },
  {
    id: "services.feature_strips",
    category: "services",
    name: "Feature Strips",
    industryAffinity: ["general", "retail", "professional_services", "portfolio"],
    brandAffinity: ["modern", "editorial", "premium", "minimalist"],
    tone: ["modern", "editorial", "premium"],
    purpose: ["explain_offer"],
    requiredAssets: ["none"],
    requiredContent: ["services"],
    strengths: ["Benefit-led", "Good hierarchy"],
    avoidWhen: ["need_photo_dense_services"],
    compatiblePatterns: [
      "hero.editorial_split",
      "hero.premium_minimal",
      "hero.bold_statement",
      "trust.partner_logos",
      "cta.minimal_cta",
      "cta.project_inquiry",
    ],
    layoutInstructions: ["full-width strips", "benefit first", "alternating subtle bg"],
    conversionStrength: 0.66,
    visualWeight: 0.55,
  },
  {
    id: "services.comparison",
    category: "services",
    name: "Comparison",
    industryAffinity: ["contractor", "local_service", "professional_services", "retail"],
    brandAffinity: ["modern", "trustworthy", "approachable"],
    tone: ["modern", "trustworthy"],
    purpose: ["explain_offer", "drive_conversion"],
    requiredAssets: ["none"],
    requiredContent: ["services"],
    strengths: ["Helps choose a package", "Conversion oriented"],
    avoidWhen: ["single_offer_only", "luxury_bespoke"],
    compatiblePatterns: [
      "hero.conversion_stack",
      "hero.dual_cta_hero",
      "trust.guarantee",
      "cta.request_quote",
      "cta.estimate",
    ],
    layoutInstructions: ["side-by-side plans", "highlight recommended", "clear price or CTA"],
    conversionStrength: 0.86,
    visualWeight: 0.62,
  },
  {
    id: "services.stacked",
    category: "services",
    name: "Stacked",
    industryAffinity: ["general", "local_service", "salon", "professional_services"],
    brandAffinity: ["approachable", "modern", "minimalist", "trustworthy"],
    tone: ["approachable", "modern", "minimalist"],
    purpose: ["explain_offer"],
    requiredAssets: ["none"],
    requiredContent: ["services"],
    strengths: ["Simple mobile stack", "Low complexity"],
    avoidWhen: ["large_service_catalog"],
    compatiblePatterns: [
      "hero.floating_card",
      "hero.conversion_stack",
      "hero.soft_gradient_service",
      "trust.google_reviews",
      "cta.schedule_visit",
      "cta.call_now",
    ],
    layoutInstructions: ["single column list", "dividers", "short blurbs"],
    conversionStrength: 0.6,
    visualWeight: 0.4,
  },
  {
    id: "services.image_focus",
    category: "services",
    name: "Image Focus",
    industryAffinity: ["landscaping", "portfolio", "salon", "restaurant", "real_estate"],
    brandAffinity: ["editorial", "premium", "handcrafted", "luxury"],
    tone: ["editorial", "premium", "handcrafted"],
    purpose: ["show_work", "explain_offer"],
    requiredAssets: ["project_photos"],
    requiredContent: ["services"],
    strengths: ["Lets imagery sell", "Premium feel"],
    avoidWhen: ["weak_photography"],
    compatiblePatterns: [
      "hero.gallery_hero",
      "hero.asymmetric_craft",
      "trust.project_highlight",
      "gallery.masonry",
      "gallery.featured_project",
      "cta.project_inquiry",
      "cta.book_consultation",
    ],
    layoutInstructions: ["large service photos", "minimal text overlays", "lightbox friendly"],
    conversionStrength: 0.7,
    visualWeight: 0.75,
  },
  {
    id: "services.premium_tiles",
    category: "services",
    name: "Premium Tiles",
    industryAffinity: ["luxury", "salon", "restaurant", "real_estate", "professional_services"],
    brandAffinity: ["luxury", "premium", "minimalist", "timeless"],
    tone: ["luxury", "premium", "minimalist"],
    purpose: ["explain_offer", "premium_positioning"],
    requiredAssets: ["hero_photo", "none"],
    requiredContent: ["services"],
    strengths: ["Quiet luxury", "Refined spacing"],
    avoidWhen: ["colorful_playful_brand", "bargain_positioning"],
    compatiblePatterns: [
      "hero.luxury_center",
      "hero.premium_minimal",
      "hero.cinematic_full_width",
      "hero.restaurant_atmosphere",
      "trust.awards",
      "cta.luxury_contact",
      "cta.reserve_table",
      "cta.minimal_cta",
      "gallery.pinterest",
    ],
    layoutInstructions: ["soft tiles", "thin borders", "restrained icons", "ample gaps"],
    conversionStrength: 0.63,
    visualWeight: 0.58,
  },
  {
    id: "services.menu_style",
    category: "services",
    name: "Menu Style",
    industryAffinity: ["restaurant", "salon", "retail"],
    brandAffinity: ["editorial", "handcrafted", "approachable", "luxury"],
    tone: ["editorial", "handcrafted", "approachable"],
    purpose: ["explain_offer", "drive_conversion"],
    requiredAssets: ["none"],
    requiredContent: ["services"],
    strengths: ["Familiar menu scanning", "Price-optional"],
    avoidWhen: ["non_menu_business"],
    compatiblePatterns: [
      "hero.restaurant_atmosphere",
      "trust.review_wall",
      "cta.reserve_table",
      "gallery.carousel",
    ],
    layoutInstructions: ["grouped items", "category headers", "optional prices"],
    conversionStrength: 0.75,
    visualWeight: 0.5,
  },
  {
    id: "services.spotlight_three",
    category: "services",
    name: "Spotlight Three",
    industryAffinity: ["general", "contractor", "landscaping", "professional_services", "salon"],
    brandAffinity: ["modern", "premium", "trustworthy", "approachable"],
    tone: ["modern", "premium", "trustworthy"],
    purpose: ["explain_offer", "drive_conversion"],
    requiredAssets: ["none"],
    requiredContent: ["services"],
    strengths: ["Forces prioritization", "Strong hierarchy"],
    avoidWhen: ["must_list_many_equal_services"],
    compatiblePatterns: [
      "hero.contractor_left",
      "hero.dual_cta_hero",
      "trust.stats_bar",
      "cta.request_quote",
      "gallery.featured_project",
    ],
    layoutInstructions: ["exactly three featured offers", "one emphasized", "rest linked later"],
    conversionStrength: 0.78,
    visualWeight: 0.6,
  },
];
