import type { DesignPattern } from "@/lib/ai/design-patterns/types";

/** Hero patterns (18) — first-viewport composition. */
export const HERO_PATTERNS: DesignPattern[] = [
  {
    id: "hero.cinematic_full_width",
    category: "hero",
    name: "Cinematic Full Width",
    industryAffinity: ["landscaping", "real_estate", "coastal", "luxury", "portfolio"],
    brandAffinity: ["luxury", "premium", "editorial", "timeless"],
    tone: ["luxury", "premium", "editorial"],
    purpose: ["first_impression", "premium_positioning"],
    requiredAssets: ["hero_photo", "aerial_photo"],
    requiredContent: ["headline", "primary_cta"],
    strengths: ["Dramatic first impression", "Showcases strong photography", "Feels agency-grade"],
    avoidWhen: ["no_hero_image", "weak_photography", "playful_brand"],
    compatiblePatterns: [
      "trust.project_highlight",
      "trust.before_after",
      "gallery.featured_project",
      "gallery.full_width",
      "cta.book_consultation",
      "cta.luxury_contact",
      "services.premium_tiles",
    ],
    layoutInstructions: [
      "full-bleed hero image",
      "minimal overlay",
      "short centered or left headline",
      "single primary CTA",
    ],
    conversionStrength: 0.72,
    visualWeight: 0.95,
  },
  {
    id: "hero.luxury_center",
    category: "hero",
    name: "Luxury Center",
    industryAffinity: ["luxury", "restaurant", "salon", "real_estate", "coastal"],
    brandAffinity: ["luxury", "premium", "minimalist", "timeless"],
    tone: ["luxury", "minimalist", "premium"],
    purpose: ["first_impression", "premium_positioning"],
    requiredAssets: ["hero_photo"],
    requiredContent: ["headline", "subheadline", "primary_cta"],
    strengths: ["Calm premium presence", "Excellent whitespace", "Brand-forward"],
    avoidWhen: ["urgent_cta_needed", "busy_imagery"],
    compatiblePatterns: [
      "trust.awards",
      "trust.review_wall",
      "services.premium_tiles",
      "gallery.pinterest",
      "cta.luxury_contact",
      "cta.reserve_table",
      "cta.minimal_cta",
    ],
    layoutInstructions: [
      "centered stack",
      "generous vertical space",
      "restrained typography",
      "soft scrim only if needed",
    ],
    conversionStrength: 0.68,
    visualWeight: 0.9,
  },
  {
    id: "hero.contractor_left",
    category: "hero",
    name: "Contractor Left",
    industryAffinity: ["contractor", "landscaping", "local_service", "general"],
    brandAffinity: ["trustworthy", "approachable", "modern", "handcrafted"],
    tone: ["trustworthy", "approachable", "modern"],
    purpose: ["first_impression", "drive_conversion", "local_proof"],
    requiredAssets: ["hero_photo", "project_photos"],
    requiredContent: ["headline", "primary_cta", "services"],
    strengths: ["Clear offer + action", "Works for local trades", "Pairs with proof"],
    avoidWhen: ["luxury_only_brand", "no_clear_cta"],
    compatiblePatterns: [
      "trust.google_reviews",
      "trust.local_badges",
      "trust.guarantee",
      "services.large_cards",
      "services.process_cards",
      "gallery.before_after",
      "cta.request_quote",
      "cta.estimate",
      "cta.call_now",
    ],
    layoutInstructions: [
      "split or left-aligned copy",
      "CTA above the fold",
      "supporting trust line",
      "practical photography",
    ],
    conversionStrength: 0.88,
    visualWeight: 0.85,
  },
  {
    id: "hero.editorial_split",
    category: "hero",
    name: "Editorial Split",
    industryAffinity: ["portfolio", "salon", "retail", "professional_services"],
    brandAffinity: ["editorial", "modern", "premium", "timeless"],
    tone: ["editorial", "modern", "premium"],
    purpose: ["first_impression", "explain_offer"],
    requiredAssets: ["hero_photo"],
    requiredContent: ["headline", "subheadline", "primary_cta"],
    strengths: ["Magazine-quality balance", "Good for storytelling", "Strong hierarchy"],
    avoidWhen: ["emergency_service", "very_short_copy_only"],
    compatiblePatterns: [
      "trust.team_trust",
      "trust.project_highlight",
      "services.alternating",
      "services.feature_strips",
      "gallery.alternating",
      "gallery.case_studies",
      "cta.project_inquiry",
      "cta.book_consultation",
    ],
    layoutInstructions: [
      "50/50 split",
      "image one side copy other",
      "editorial type scale",
      "asymmetric but balanced",
    ],
    conversionStrength: 0.7,
    visualWeight: 0.88,
  },
  {
    id: "hero.floating_card",
    category: "hero",
    name: "Floating Card",
    industryAffinity: ["professional_services", "salon", "retail", "general"],
    brandAffinity: ["modern", "approachable", "premium", "playful"],
    tone: ["modern", "approachable", "premium"],
    purpose: ["first_impression", "drive_conversion"],
    requiredAssets: ["hero_photo"],
    requiredContent: ["headline", "primary_cta"],
    strengths: ["Focuses attention on the offer card", "Works on busy photos", "Mobile-friendly"],
    avoidWhen: ["ultra_minimal_brand", "no_hero_image"],
    compatiblePatterns: [
      "trust.google_reviews",
      "trust.review_wall",
      "services.icon_grid",
      "services.stacked",
      "gallery.grid",
      "cta.schedule_visit",
      "cta.request_quote",
    ],
    layoutInstructions: [
      "background image",
      "elevated content card",
      "card holds headline + CTA",
      "soft shadow restraint",
    ],
    conversionStrength: 0.8,
    visualWeight: 0.82,
  },
  {
    id: "hero.coastal_service",
    category: "hero",
    name: "Coastal Service",
    industryAffinity: ["coastal", "landscaping", "contractor", "local_service", "restaurant"],
    brandAffinity: ["approachable", "trustworthy", "timeless", "handcrafted"],
    tone: ["approachable", "trustworthy", "timeless"],
    purpose: ["first_impression", "local_proof", "drive_conversion"],
    requiredAssets: ["hero_photo"],
    requiredContent: ["headline", "primary_cta"],
    strengths: ["Warm local feel", "Balances lifestyle + service", "Inviting CTA"],
    avoidWhen: ["industrial_tone", "corporate_only"],
    compatiblePatterns: [
      "trust.local_badges",
      "trust.google_reviews",
      "services.large_cards",
      "gallery.masonry",
      "cta.schedule_visit",
      "cta.book_consultation",
    ],
    layoutInstructions: [
      "airy hero",
      "natural light photography",
      "friendly headline",
      "secondary local cue",
    ],
    conversionStrength: 0.78,
    visualWeight: 0.84,
  },
  {
    id: "hero.premium_minimal",
    category: "hero",
    name: "Premium Minimal",
    industryAffinity: ["luxury", "professional_services", "salon", "general"],
    brandAffinity: ["minimalist", "luxury", "premium", "timeless"],
    tone: ["minimalist", "luxury", "premium"],
    purpose: ["first_impression", "premium_positioning"],
    requiredAssets: ["hero_photo", "none"],
    requiredContent: ["headline", "primary_cta"],
    strengths: ["Quiet confidence", "Excellent readability", "Timeless"],
    avoidWhen: ["needs_high_energy", "weak_typography"],
    compatiblePatterns: [
      "trust.awards",
      "trust.partner_logos",
      "services.premium_tiles",
      "services.feature_strips",
      "gallery.full_width",
      "cta.minimal_cta",
      "cta.luxury_contact",
    ],
    layoutInstructions: [
      "lots of negative space",
      "one idea",
      "thin accent line optional",
      "understated CTA",
    ],
    conversionStrength: 0.65,
    visualWeight: 0.78,
  },
  {
    id: "hero.process_hero",
    category: "hero",
    name: "Process Hero",
    industryAffinity: ["contractor", "landscaping", "professional_services", "local_service"],
    brandAffinity: ["trustworthy", "modern", "approachable", "handcrafted"],
    tone: ["trustworthy", "modern", "approachable"],
    purpose: ["explain_offer", "build_trust", "first_impression"],
    requiredAssets: ["project_photos", "hero_photo"],
    requiredContent: ["headline", "process_steps", "primary_cta"],
    strengths: ["Makes the journey clear", "Reduces uncertainty", "Good for complex services"],
    avoidWhen: ["impulse_purchase", "luxury_mystery_brand"],
    compatiblePatterns: [
      "trust.guarantee",
      "trust.certifications",
      "services.process_cards",
      "services.timeline",
      "gallery.timeline",
      "cta.request_quote",
      "cta.estimate",
    ],
    layoutInstructions: [
      "hero with 3-step cue",
      "numbered process near fold",
      "CTA after steps",
    ],
    conversionStrength: 0.82,
    visualWeight: 0.8,
  },
  {
    id: "hero.gallery_hero",
    category: "hero",
    name: "Gallery Hero",
    industryAffinity: ["landscaping", "portfolio", "contractor", "real_estate", "salon"],
    brandAffinity: ["editorial", "premium", "modern", "handcrafted"],
    tone: ["editorial", "premium", "modern"],
    purpose: ["show_work", "first_impression"],
    requiredAssets: ["project_photos", "hero_photo"],
    requiredContent: ["headline", "primary_cta"],
    strengths: ["Leads with craft", "Ideal when photos are the product", "High engagement"],
    avoidWhen: ["few_photos", "text_heavy_offer"],
    compatiblePatterns: [
      "gallery.masonry",
      "gallery.featured_project",
      "gallery.carousel",
      "trust.project_highlight",
      "services.image_focus",
      "cta.project_inquiry",
      "cta.book_consultation",
    ],
    layoutInstructions: [
      "hero as featured gallery frame",
      "secondary thumbnails optional",
      "copy overlays carefully",
    ],
    conversionStrength: 0.74,
    visualWeight: 0.92,
  },
  {
    id: "hero.before_after_hero",
    category: "hero",
    name: "Before / After Hero",
    industryAffinity: ["landscaping", "contractor", "salon", "local_service"],
    brandAffinity: ["trustworthy", "handcrafted", "approachable", "modern"],
    tone: ["trustworthy", "handcrafted", "approachable"],
    purpose: ["show_work", "build_trust", "first_impression"],
    requiredAssets: ["before_after", "project_photos"],
    requiredContent: ["headline", "primary_cta"],
    strengths: ["Instant transformation proof", "High conversion for trades", "Memorable"],
    avoidWhen: ["no_before_after_assets", "luxury_subtle_brand"],
    compatiblePatterns: [
      "trust.before_after",
      "gallery.before_after",
      "services.process_cards",
      "cta.estimate",
      "cta.request_quote",
      "cta.schedule_visit",
    ],
    layoutInstructions: [
      "paired before/after in hero",
      "clear labels",
      "CTA tied to transformation",
    ],
    conversionStrength: 0.9,
    visualWeight: 0.9,
  },
  {
    id: "hero.trust_first_hero",
    category: "hero",
    name: "Trust-First Hero",
    industryAffinity: ["professional_services", "contractor", "local_service", "general"],
    brandAffinity: ["trustworthy", "approachable", "modern", "timeless"],
    tone: ["trustworthy", "approachable"],
    purpose: ["build_trust", "first_impression", "local_proof"],
    requiredAssets: ["hero_photo", "none"],
    requiredContent: ["headline", "reviews", "primary_cta"],
    strengths: ["Leads with social proof", "Calms skeptical visitors", "Local-friendly"],
    avoidWhen: ["no_reviews", "brand_new_business_no_proof"],
    compatiblePatterns: [
      "trust.google_reviews",
      "trust.review_wall",
      "trust.local_badges",
      "services.icon_grid",
      "cta.call_now",
      "cta.schedule_visit",
    ],
    layoutInstructions: [
      "rating or review snippet in hero",
      "supportive headline",
      "CTA secondary to trust cue",
    ],
    conversionStrength: 0.86,
    visualWeight: 0.8,
  },
  {
    id: "hero.conversion_stack",
    category: "hero",
    name: "Conversion Stack",
    industryAffinity: ["local_service", "contractor", "restaurant", "general"],
    brandAffinity: ["modern", "approachable", "trustworthy", "playful"],
    tone: ["modern", "approachable", "trustworthy"],
    purpose: ["drive_conversion", "urgency", "first_impression"],
    requiredAssets: ["hero_photo", "none"],
    requiredContent: ["headline", "primary_cta", "contact"],
    strengths: ["Maximizes action clarity", "Great for lead gen", "Mobile CTA prominence"],
    avoidWhen: ["luxury_soft_sell", "portfolio_only"],
    compatiblePatterns: [
      "trust.guarantee",
      "trust.google_reviews",
      "services.stacked",
      "services.comparison",
      "cta.emergency_service",
      "cta.call_now",
      "cta.request_quote",
    ],
    layoutInstructions: [
      "stacked offer + benefits + CTA",
      "phone or form cue early",
      "short benefit bullets",
    ],
    conversionStrength: 0.93,
    visualWeight: 0.86,
  },
  {
    id: "hero.restaurant_atmosphere",
    category: "hero",
    name: "Restaurant Atmosphere",
    industryAffinity: ["restaurant", "coastal", "luxury"],
    brandAffinity: ["luxury", "editorial", "handcrafted", "approachable"],
    tone: ["luxury", "editorial", "handcrafted"],
    purpose: ["first_impression", "premium_positioning", "drive_conversion"],
    requiredAssets: ["hero_photo"],
    requiredContent: ["headline", "primary_cta"],
    strengths: ["Appetite + ambiance", "Reservation-ready", "Sensory"],
    avoidWhen: ["no_food_or_interior_photos"],
    compatiblePatterns: [
      "trust.awards",
      "trust.review_wall",
      "gallery.full_width",
      "gallery.carousel",
      "cta.reserve_table",
      "cta.luxury_contact",
      "services.premium_tiles",
    ],
    layoutInstructions: [
      "atmospheric photography",
      "menu or reserve CTA",
      "evening/warm lighting preferred",
    ],
    conversionStrength: 0.84,
    visualWeight: 0.93,
  },
  {
    id: "hero.local_banner",
    category: "hero",
    name: "Local Banner",
    industryAffinity: ["local_service", "contractor", "landscaping", "retail", "general"],
    brandAffinity: ["approachable", "trustworthy", "modern", "handcrafted"],
    tone: ["approachable", "trustworthy"],
    purpose: ["local_proof", "first_impression", "drive_conversion"],
    requiredAssets: ["hero_photo", "none"],
    requiredContent: ["headline", "primary_cta"],
    strengths: ["Signals community presence", "Simple and clear", "Fast to scan"],
    avoidWhen: ["national_luxury_brand"],
    compatiblePatterns: [
      "trust.local_badges",
      "trust.partner_logos",
      "services.icon_grid",
      "services.large_cards",
      "gallery.grid",
      "cta.call_now",
      "cta.schedule_visit",
    ],
    layoutInstructions: [
      "location cue in hero",
      "service area line",
      "direct CTA",
    ],
    conversionStrength: 0.8,
    visualWeight: 0.75,
  },
  {
    id: "hero.bold_statement",
    category: "hero",
    name: "Bold Statement",
    industryAffinity: ["portfolio", "retail", "general"],
    brandAffinity: ["modern", "playful", "editorial", "premium"],
    tone: ["modern", "playful", "editorial"],
    purpose: ["first_impression", "premium_positioning"],
    requiredAssets: ["hero_photo", "none"],
    requiredContent: ["headline", "primary_cta"],
    strengths: ["Memorable voice", "Strong brand personality", "Differentiation"],
    avoidWhen: ["conservative_professional_services", "weak_headline"],
    compatiblePatterns: [
      "trust.team_trust",
      "services.feature_strips",
      "gallery.pinterest",
      "gallery.masonry",
      "cta.project_inquiry",
      "cta.minimal_cta",
    ],
    layoutInstructions: [
      "oversized headline",
      "short supporting line",
      "high-contrast type",
    ],
    conversionStrength: 0.66,
    visualWeight: 0.88,
  },
  {
    id: "hero.soft_gradient_service",
    category: "hero",
    name: "Soft Gradient Service",
    industryAffinity: ["salon", "professional_services", "general"],
    brandAffinity: ["approachable", "modern", "minimalist", "trustworthy"],
    tone: ["approachable", "modern", "minimalist"],
    purpose: ["first_impression", "drive_conversion"],
    requiredAssets: ["none", "hero_photo"],
    requiredContent: ["headline", "subheadline", "primary_cta"],
    strengths: ["Works without perfect photography", "Calm and readable", "Flexible"],
    avoidWhen: ["photo_is_the_product"],
    compatiblePatterns: [
      "trust.certifications",
      "trust.google_reviews",
      "services.icon_grid",
      "services.stacked",
      "cta.schedule_visit",
      "cta.book_consultation",
    ],
    layoutInstructions: [
      "soft brand gradient or wash",
      "optional small photo",
      "clear service promise",
    ],
    conversionStrength: 0.76,
    visualWeight: 0.7,
  },
  {
    id: "hero.dual_cta_hero",
    category: "hero",
    name: "Dual CTA Hero",
    industryAffinity: ["contractor", "local_service", "real_estate", "general"],
    brandAffinity: ["modern", "trustworthy", "approachable", "premium"],
    tone: ["modern", "trustworthy", "approachable"],
    purpose: ["drive_conversion", "first_impression"],
    requiredAssets: ["hero_photo"],
    requiredContent: ["headline", "primary_cta", "contact"],
    strengths: ["Supports call + form paths", "Good for mixed intent", "Practical"],
    avoidWhen: ["single_cta_luxury"],
    compatiblePatterns: [
      "trust.google_reviews",
      "trust.guarantee",
      "services.comparison",
      "services.large_cards",
      "cta.request_quote",
      "cta.call_now",
      "cta.estimate",
    ],
    layoutInstructions: [
      "primary + secondary CTA",
      "clear hierarchy between actions",
      "avoid equal visual weight on both",
    ],
    conversionStrength: 0.87,
    visualWeight: 0.83,
  },
  {
    id: "hero.asymmetric_craft",
    category: "hero",
    name: "Asymmetric Craft",
    industryAffinity: ["landscaping", "portfolio", "salon", "contractor"],
    brandAffinity: ["handcrafted", "editorial", "premium", "timeless"],
    tone: ["handcrafted", "editorial", "premium"],
    purpose: ["first_impression", "show_work", "premium_positioning"],
    requiredAssets: ["project_photos", "hero_photo"],
    requiredContent: ["headline", "primary_cta"],
    strengths: ["Artisan feel", "Unique composition", "Elevates craft businesses"],
    avoidWhen: ["strict_corporate", "low_image_quality"],
    compatiblePatterns: [
      "trust.project_highlight",
      "services.image_focus",
      "services.alternating",
      "gallery.masonry",
      "gallery.case_studies",
      "cta.project_inquiry",
      "cta.book_consultation",
    ],
    layoutInstructions: [
      "asymmetric image crop",
      "craft-forward typography",
      "offset CTA",
    ],
    conversionStrength: 0.73,
    visualWeight: 0.89,
  },
];
