import type { DesignPattern } from "@/lib/ai/design-patterns/types";

/** Gallery patterns (12). */
export const GALLERY_PATTERNS: DesignPattern[] = [
  {
    id: "gallery.masonry",
    category: "gallery",
    name: "Masonry",
    industryAffinity: ["landscaping", "portfolio", "salon", "coastal", "contractor"],
    brandAffinity: ["editorial", "handcrafted", "premium", "modern"],
    tone: ["editorial", "handcrafted", "premium"],
    purpose: ["show_work"],
    requiredAssets: ["project_photos"],
    requiredContent: [],
    strengths: ["Organic photo rhythm", "Feels curated"],
    avoidWhen: ["few_photos", "uniform_crop_required"],
    compatiblePatterns: [
      "hero.gallery_hero",
      "hero.coastal_service",
      "hero.asymmetric_craft",
      "services.image_focus",
      "trust.project_highlight",
      "cta.project_inquiry",
    ],
    layoutInstructions: ["varied heights", "tight gutters", "lightbox"],
    conversionStrength: 0.6,
    visualWeight: 0.72,
  },
  {
    id: "gallery.carousel",
    category: "gallery",
    name: "Carousel",
    industryAffinity: ["restaurant", "retail", "salon", "general", "real_estate"],
    brandAffinity: ["modern", "approachable", "premium", "playful"],
    tone: ["modern", "approachable", "premium"],
    purpose: ["show_work"],
    requiredAssets: ["project_photos"],
    requiredContent: [],
    strengths: ["Focuses one image at a time", "Good on mobile"],
    avoidWhen: ["need_all_visible_at_once"],
    compatiblePatterns: [
      "hero.restaurant_atmosphere",
      "hero.gallery_hero",
      "trust.review_wall",
      "services.menu_style",
      "cta.reserve_table",
      "cta.schedule_visit",
    ],
    layoutInstructions: ["one hero slide", "peek next", "dots or arrows"],
    conversionStrength: 0.58,
    visualWeight: 0.65,
  },
  {
    id: "gallery.featured_project",
    category: "gallery",
    name: "Featured Project",
    industryAffinity: ["landscaping", "contractor", "portfolio", "real_estate"],
    brandAffinity: ["premium", "editorial", "handcrafted", "trustworthy"],
    tone: ["premium", "editorial", "handcrafted"],
    purpose: ["show_work", "build_trust"],
    requiredAssets: ["project_photos"],
    requiredContent: [],
    strengths: ["Deep dive on best work", "Narrative friendly"],
    avoidWhen: ["no_standout_project"],
    compatiblePatterns: [
      "hero.cinematic_full_width",
      "hero.gallery_hero",
      "trust.project_highlight",
      "services.image_focus",
      "services.spotlight_three",
      "cta.project_inquiry",
      "cta.book_consultation",
    ],
    layoutInstructions: ["one large feature", "supporting thumbs", "case caption"],
    conversionStrength: 0.72,
    visualWeight: 0.78,
  },
  {
    id: "gallery.before_after",
    category: "gallery",
    name: "Before/After",
    industryAffinity: ["landscaping", "contractor", "salon", "local_service"],
    brandAffinity: ["trustworthy", "handcrafted", "approachable", "modern"],
    tone: ["trustworthy", "handcrafted"],
    purpose: ["show_work", "build_trust"],
    requiredAssets: ["before_after"],
    requiredContent: [],
    strengths: ["Proof-heavy", "High persuasion"],
    avoidWhen: ["no_before_after_assets"],
    compatiblePatterns: [
      "hero.before_after_hero",
      "trust.before_after",
      "services.process_cards",
      "cta.estimate",
      "cta.request_quote",
    ],
    layoutInstructions: ["slider or pairs", "labels", "project names"],
    conversionStrength: 0.88,
    visualWeight: 0.74,
  },
  {
    id: "gallery.timeline",
    category: "gallery",
    name: "Timeline",
    industryAffinity: ["contractor", "landscaping", "portfolio"],
    brandAffinity: ["timeless", "trustworthy", "editorial", "modern"],
    tone: ["timeless", "trustworthy", "editorial"],
    purpose: ["show_work", "explain_offer"],
    requiredAssets: ["project_photos"],
    requiredContent: ["process_steps"],
    strengths: ["Shows progress", "Educational"],
    avoidWhen: ["unordered_portfolio"],
    compatiblePatterns: [
      "hero.process_hero",
      "services.timeline",
      "services.process_cards",
      "cta.book_consultation",
    ],
    layoutInstructions: ["chrono project frames", "phase captions"],
    conversionStrength: 0.64,
    visualWeight: 0.6,
  },
  {
    id: "gallery.alternating",
    category: "gallery",
    name: "Alternating",
    industryAffinity: ["portfolio", "salon", "professional_services", "landscaping"],
    brandAffinity: ["editorial", "premium", "modern", "handcrafted"],
    tone: ["editorial", "premium"],
    purpose: ["show_work"],
    requiredAssets: ["project_photos"],
    requiredContent: [],
    strengths: ["Readable storytelling", "Balanced"],
    avoidWhen: ["image_only_moodboard"],
    compatiblePatterns: [
      "hero.editorial_split",
      "services.alternating",
      "trust.team_trust",
      "cta.project_inquiry",
    ],
    layoutInstructions: ["image/text bands", "consistent margins"],
    conversionStrength: 0.62,
    visualWeight: 0.68,
  },
  {
    id: "gallery.pinterest",
    category: "gallery",
    name: "Pinterest",
    industryAffinity: ["salon", "retail", "portfolio", "restaurant", "luxury"],
    brandAffinity: ["playful", "editorial", "premium", "modern"],
    tone: ["playful", "editorial", "premium"],
    purpose: ["show_work", "premium_positioning"],
    requiredAssets: ["project_photos"],
    requiredContent: [],
    strengths: ["Aspirational browsing", "Discovery feel"],
    avoidWhen: ["corporate_conservative"],
    compatiblePatterns: [
      "hero.luxury_center",
      "hero.bold_statement",
      "services.premium_tiles",
      "cta.luxury_contact",
      "cta.minimal_cta",
    ],
    layoutInstructions: ["dense pin grid", "soft radii", "hover titles"],
    conversionStrength: 0.55,
    visualWeight: 0.7,
  },
  {
    id: "gallery.full_width",
    category: "gallery",
    name: "Full-width",
    industryAffinity: ["luxury", "real_estate", "landscaping", "restaurant", "portfolio"],
    brandAffinity: ["luxury", "editorial", "premium", "timeless"],
    tone: ["luxury", "editorial", "premium"],
    purpose: ["show_work", "premium_positioning"],
    requiredAssets: ["hero_photo", "project_photos"],
    requiredContent: [],
    strengths: ["Immersive", "Agency cinematic"],
    avoidWhen: ["weak_wide_photos"],
    compatiblePatterns: [
      "hero.cinematic_full_width",
      "hero.premium_minimal",
      "hero.restaurant_atmosphere",
      "trust.awards",
      "cta.luxury_contact",
      "services.premium_tiles",
    ],
    layoutInstructions: ["edge-to-edge frames", "minimal chrome", "slow scroll moments"],
    conversionStrength: 0.58,
    visualWeight: 0.85,
  },
  {
    id: "gallery.grid",
    category: "gallery",
    name: "Grid",
    industryAffinity: ["general", "local_service", "contractor", "retail", "salon"],
    brandAffinity: ["modern", "approachable", "trustworthy", "minimalist"],
    tone: ["modern", "approachable", "minimalist"],
    purpose: ["show_work"],
    requiredAssets: ["project_photos"],
    requiredContent: [],
    strengths: ["Orderly", "Predictable", "Easy to maintain"],
    avoidWhen: ["need_editorial_asymmetry"],
    compatiblePatterns: [
      "hero.floating_card",
      "hero.local_banner",
      "services.large_cards",
      "trust.local_badges",
      "cta.schedule_visit",
      "cta.request_quote",
    ],
    layoutInstructions: ["uniform cells", "2–4 columns", "equal crops"],
    conversionStrength: 0.57,
    visualWeight: 0.55,
  },
  {
    id: "gallery.case_studies",
    category: "gallery",
    name: "Case Studies",
    industryAffinity: ["portfolio", "professional_services", "contractor", "landscaping"],
    brandAffinity: ["editorial", "premium", "trustworthy", "timeless"],
    tone: ["editorial", "premium", "trustworthy"],
    purpose: ["show_work", "build_trust", "explain_offer"],
    requiredAssets: ["project_photos"],
    requiredContent: ["testimonials"],
    strengths: ["Outcome storytelling", "B2B friendly"],
    avoidWhen: ["no_project_narratives"],
    compatiblePatterns: [
      "hero.editorial_split",
      "hero.asymmetric_craft",
      "trust.project_highlight",
      "trust.press_mentions",
      "services.alternating",
      "cta.project_inquiry",
      "cta.book_consultation",
    ],
    layoutInstructions: ["problem → solution → result", "metrics if available"],
    conversionStrength: 0.76,
    visualWeight: 0.7,
  },
  {
    id: "gallery.lightbox_grid",
    category: "gallery",
    name: "Lightbox Grid",
    industryAffinity: ["landscaping", "contractor", "portfolio", "salon", "general"],
    brandAffinity: ["modern", "premium", "handcrafted", "approachable"],
    tone: ["modern", "premium", "handcrafted"],
    purpose: ["show_work"],
    requiredAssets: ["project_photos"],
    requiredContent: [],
    strengths: ["Detail on demand", "Keeps page calm"],
    avoidWhen: ["no_full_res_assets"],
    compatiblePatterns: [
      "hero.gallery_hero",
      "hero.contractor_left",
      "services.image_focus",
      "cta.project_inquiry",
      "trust.before_after",
    ],
    layoutInstructions: ["compact grid", "click to expand", "captions in viewer"],
    conversionStrength: 0.61,
    visualWeight: 0.58,
  },
  {
    id: "gallery.mosaic_feature",
    category: "gallery",
    name: "Mosaic Feature",
    industryAffinity: ["landscaping", "real_estate", "portfolio", "restaurant"],
    brandAffinity: ["editorial", "luxury", "premium", "modern"],
    tone: ["editorial", "luxury", "premium"],
    purpose: ["show_work", "premium_positioning"],
    requiredAssets: ["project_photos", "aerial_photo"],
    requiredContent: [],
    strengths: ["Heroic collage", "Highlights best shots"],
    avoidWhen: ["under_four_photos"],
    compatiblePatterns: [
      "hero.cinematic_full_width",
      "hero.gallery_hero",
      "services.premium_tiles",
      "cta.luxury_contact",
      "trust.awards",
    ],
    layoutInstructions: ["1 large + satellites", "tight mosaic", "shared theme"],
    conversionStrength: 0.63,
    visualWeight: 0.8,
  },
];
