import type { DesignPattern } from "@/lib/ai/design-patterns/types";

/** CTA patterns (12). */
export const CTA_PATTERNS: DesignPattern[] = [
  {
    id: "cta.book_consultation",
    category: "cta",
    name: "Book Consultation",
    industryAffinity: ["professional_services", "salon", "landscaping", "contractor", "general"],
    brandAffinity: ["premium", "trustworthy", "modern", "approachable"],
    tone: ["premium", "trustworthy", "modern"],
    purpose: ["drive_conversion"],
    requiredAssets: ["none"],
    requiredContent: ["primary_cta", "contact"],
    strengths: ["Low-pressure next step", "Fits advisory services"],
    avoidWhen: ["emergency_only"],
    compatiblePatterns: [
      "hero.cinematic_full_width",
      "hero.editorial_split",
      "hero.coastal_service",
      "hero.soft_gradient_service",
      "trust.certifications",
      "trust.team_trust",
      "services.alternating",
      "gallery.case_studies",
    ],
    layoutInstructions: ["consultation framing", "calendar or form cue", "calm urgency"],
    conversionStrength: 0.82,
    visualWeight: 0.55,
  },
  {
    id: "cta.estimate",
    category: "cta",
    name: "Estimate",
    industryAffinity: ["contractor", "landscaping", "local_service"],
    brandAffinity: ["trustworthy", "approachable", "modern", "handcrafted"],
    tone: ["trustworthy", "approachable"],
    purpose: ["drive_conversion"],
    requiredAssets: ["none"],
    requiredContent: ["primary_cta", "contact"],
    strengths: ["Trade-standard ask", "Pairs with before/after"],
    avoidWhen: ["restaurant_or_retail_browse"],
    compatiblePatterns: [
      "hero.contractor_left",
      "hero.before_after_hero",
      "hero.process_hero",
      "trust.before_after",
      "trust.guarantee",
      "services.process_cards",
      "gallery.before_after",
    ],
    layoutInstructions: ["free estimate language", "photo upload optional", "phone backup"],
    conversionStrength: 0.9,
    visualWeight: 0.58,
  },
  {
    id: "cta.emergency_service",
    category: "cta",
    name: "Emergency Service",
    industryAffinity: ["local_service", "contractor", "general"],
    brandAffinity: ["trustworthy", "modern", "approachable"],
    tone: ["trustworthy", "approachable"],
    purpose: ["urgency", "drive_conversion"],
    requiredAssets: ["none"],
    requiredContent: ["primary_cta", "contact"],
    strengths: ["High intent capture", "Clear urgency"],
    avoidWhen: ["luxury_soft_sell", "no_emergency_offering"],
    compatiblePatterns: [
      "hero.conversion_stack",
      "trust.guarantee",
      "services.stacked",
      "cta.call_now",
    ],
    layoutInstructions: ["urgent color accent sparingly", "phone dominant", "hours visible"],
    conversionStrength: 0.95,
    visualWeight: 0.7,
  },
  {
    id: "cta.reserve_table",
    category: "cta",
    name: "Reserve Table",
    industryAffinity: ["restaurant", "coastal", "luxury"],
    brandAffinity: ["luxury", "editorial", "handcrafted", "approachable"],
    tone: ["luxury", "editorial", "handcrafted"],
    purpose: ["drive_conversion"],
    requiredAssets: ["none"],
    requiredContent: ["primary_cta", "contact"],
    strengths: ["Dining-native action", "Pairs with atmosphere hero"],
    avoidWhen: ["non_restaurant"],
    compatiblePatterns: [
      "hero.restaurant_atmosphere",
      "hero.luxury_center",
      "trust.review_wall",
      "trust.awards",
      "services.menu_style",
      "services.premium_tiles",
      "gallery.carousel",
      "gallery.full_width",
    ],
    layoutInstructions: ["reserve CTA", "party size/time optional", "warm tone"],
    conversionStrength: 0.88,
    visualWeight: 0.6,
  },
  {
    id: "cta.call_now",
    category: "cta",
    name: "Call Now",
    industryAffinity: ["local_service", "contractor", "landscaping", "salon", "general"],
    brandAffinity: ["approachable", "trustworthy", "modern"],
    tone: ["approachable", "trustworthy"],
    purpose: ["drive_conversion", "urgency"],
    requiredAssets: ["none"],
    requiredContent: ["contact", "primary_cta"],
    strengths: ["Immediate contact", "Mobile conversion"],
    avoidWhen: ["async_only_brand"],
    compatiblePatterns: [
      "hero.contractor_left",
      "hero.trust_first_hero",
      "hero.conversion_stack",
      "hero.local_banner",
      "hero.dual_cta_hero",
      "trust.google_reviews",
      "services.stacked",
    ],
    layoutInstructions: ["click-to-call", "number visible", "short reassurance"],
    conversionStrength: 0.92,
    visualWeight: 0.62,
  },
  {
    id: "cta.project_inquiry",
    category: "cta",
    name: "Project Inquiry",
    industryAffinity: ["portfolio", "landscaping", "contractor", "professional_services"],
    brandAffinity: ["premium", "editorial", "handcrafted", "modern"],
    tone: ["premium", "editorial", "handcrafted"],
    purpose: ["drive_conversion"],
    requiredAssets: ["none"],
    requiredContent: ["primary_cta", "contact"],
    strengths: ["Fits custom work", "Qualifies leads"],
    avoidWhen: ["commodity_quick_sale"],
    compatiblePatterns: [
      "hero.editorial_split",
      "hero.gallery_hero",
      "hero.asymmetric_craft",
      "hero.bold_statement",
      "trust.project_highlight",
      "services.image_focus",
      "gallery.featured_project",
      "gallery.case_studies",
      "gallery.masonry",
    ],
    layoutInstructions: ["inquiry form", "project details fields", "portfolio context"],
    conversionStrength: 0.8,
    visualWeight: 0.55,
  },
  {
    id: "cta.request_quote",
    category: "cta",
    name: "Request Quote",
    industryAffinity: ["contractor", "landscaping", "local_service", "general"],
    brandAffinity: ["trustworthy", "modern", "approachable", "handcrafted"],
    tone: ["trustworthy", "modern", "approachable"],
    purpose: ["drive_conversion"],
    requiredAssets: ["none"],
    requiredContent: ["primary_cta", "contact"],
    strengths: ["Universal trade CTA", "Pairs with most service layouts"],
    avoidWhen: ["restaurant"],
    compatiblePatterns: [
      "hero.contractor_left",
      "hero.conversion_stack",
      "hero.dual_cta_hero",
      "hero.floating_card",
      "trust.google_reviews",
      "trust.guarantee",
      "trust.stats_bar",
      "services.large_cards",
      "services.comparison",
      "services.spotlight_three",
      "gallery.grid",
      "gallery.before_after",
    ],
    layoutInstructions: ["quote form", "service type select", "timeline field optional"],
    conversionStrength: 0.91,
    visualWeight: 0.6,
  },
  {
    id: "cta.schedule_visit",
    category: "cta",
    name: "Schedule Visit",
    industryAffinity: ["local_service", "salon", "real_estate", "contractor", "landscaping"],
    brandAffinity: ["approachable", "trustworthy", "modern", "premium"],
    tone: ["approachable", "trustworthy", "modern"],
    purpose: ["drive_conversion"],
    requiredAssets: ["none"],
    requiredContent: ["primary_cta", "contact"],
    strengths: ["In-person conversion", "Local businesses"],
    avoidWhen: ["fully_remote_service"],
    compatiblePatterns: [
      "hero.coastal_service",
      "hero.floating_card",
      "hero.local_banner",
      "hero.soft_gradient_service",
      "trust.local_badges",
      "trust.review_wall",
      "services.icon_grid",
      "services.stacked",
      "gallery.carousel",
      "gallery.grid",
    ],
    layoutInstructions: ["visit scheduling", "address or service area", "calendar cue"],
    conversionStrength: 0.84,
    visualWeight: 0.55,
  },
  {
    id: "cta.luxury_contact",
    category: "cta",
    name: "Luxury Contact",
    industryAffinity: ["luxury", "restaurant", "real_estate", "salon", "portfolio"],
    brandAffinity: ["luxury", "premium", "minimalist", "timeless", "editorial"],
    tone: ["luxury", "premium", "minimalist"],
    purpose: ["drive_conversion", "premium_positioning"],
    requiredAssets: ["none"],
    requiredContent: ["primary_cta", "contact"],
    strengths: ["Soft ask", "Matches luxury heroes"],
    avoidWhen: ["hard_sell_trade", "colorful_card_grids"],
    compatiblePatterns: [
      "hero.luxury_center",
      "hero.cinematic_full_width",
      "hero.premium_minimal",
      "hero.restaurant_atmosphere",
      "trust.awards",
      "trust.press_mentions",
      "services.premium_tiles",
      "gallery.full_width",
      "gallery.pinterest",
      "gallery.mosaic_feature",
    ],
    layoutInstructions: ["understated button", "concierge language", "whitespace"],
    conversionStrength: 0.7,
    visualWeight: 0.45,
  },
  {
    id: "cta.minimal_cta",
    category: "cta",
    name: "Minimal CTA",
    industryAffinity: ["luxury", "professional_services", "portfolio", "general"],
    brandAffinity: ["minimalist", "luxury", "timeless", "premium"],
    tone: ["minimalist", "luxury", "timeless"],
    purpose: ["drive_conversion", "premium_positioning"],
    requiredAssets: ["none"],
    requiredContent: ["primary_cta"],
    strengths: ["Quiet close", "Doesn't compete with work"],
    avoidWhen: ["needs_aggressive_conversion"],
    compatiblePatterns: [
      "hero.premium_minimal",
      "hero.luxury_center",
      "hero.bold_statement",
      "trust.partner_logos",
      "services.feature_strips",
      "services.premium_tiles",
      "gallery.pinterest",
    ],
    layoutInstructions: ["single text link or slim button", "no banner shout"],
    conversionStrength: 0.58,
    visualWeight: 0.3,
  },
  {
    id: "cta.get_started",
    category: "cta",
    name: "Get Started",
    industryAffinity: ["general", "professional_services", "retail", "salon"],
    brandAffinity: ["modern", "approachable", "playful", "premium"],
    tone: ["modern", "approachable", "playful"],
    purpose: ["drive_conversion"],
    requiredAssets: ["none"],
    requiredContent: ["primary_cta"],
    strengths: ["Friendly default", "Broadly compatible"],
    avoidWhen: ["ultra_luxury_voice"],
    compatiblePatterns: [
      "hero.floating_card",
      "hero.soft_gradient_service",
      "trust.review_wall",
      "services.icon_grid",
      "services.large_cards",
      "gallery.grid",
    ],
    layoutInstructions: ["get started label", "short benefit line", "form or next step"],
    conversionStrength: 0.77,
    visualWeight: 0.5,
  },
  {
    id: "cta.contact_band",
    category: "cta",
    name: "Contact Band",
    industryAffinity: ["general", "local_service", "contractor", "professional_services"],
    brandAffinity: ["modern", "trustworthy", "approachable", "timeless"],
    tone: ["modern", "trustworthy", "approachable"],
    purpose: ["drive_conversion"],
    requiredAssets: ["none"],
    requiredContent: ["contact", "primary_cta"],
    strengths: ["Footer-adjacent closer", "Multiple contact methods"],
    avoidWhen: ["single_subtle_luxury_close"],
    compatiblePatterns: [
      "hero.local_banner",
      "hero.dual_cta_hero",
      "trust.local_badges",
      "services.large_cards",
      "gallery.grid",
    ],
    layoutInstructions: ["full-width band", "phone email form", "map optional"],
    conversionStrength: 0.8,
    visualWeight: 0.52,
  },
];
