import type { DesignPattern } from "@/lib/ai/design-patterns/types";

/** Trust patterns (12). */
export const TRUST_PATTERNS: DesignPattern[] = [
  {
    id: "trust.review_wall",
    category: "trust",
    name: "Review Wall",
    industryAffinity: ["general", "restaurant", "salon", "local_service", "retail"],
    brandAffinity: ["approachable", "trustworthy", "modern", "playful"],
    tone: ["approachable", "trustworthy"],
    purpose: ["build_trust", "local_proof"],
    requiredAssets: ["none"],
    requiredContent: ["testimonials", "reviews"],
    strengths: ["Social proof density", "Builds momentum after hero"],
    avoidWhen: ["no_reviews", "luxury_quiet_brand"],
    compatiblePatterns: [
      "hero.luxury_center",
      "hero.floating_card",
      "hero.restaurant_atmosphere",
      "cta.reserve_table",
      "cta.schedule_visit",
      "services.large_cards",
    ],
    layoutInstructions: ["grid of short quotes", "ratings visible", "faces optional"],
    conversionStrength: 0.78,
    visualWeight: 0.55,
  },
  {
    id: "trust.google_reviews",
    category: "trust",
    name: "Google Reviews",
    industryAffinity: ["local_service", "contractor", "landscaping", "restaurant", "salon"],
    brandAffinity: ["trustworthy", "approachable", "modern"],
    tone: ["trustworthy", "approachable"],
    purpose: ["build_trust", "local_proof", "drive_conversion"],
    requiredAssets: ["none"],
    requiredContent: ["reviews"],
    strengths: ["Familiar third-party proof", "High local conversion"],
    avoidWhen: ["no_google_presence"],
    compatiblePatterns: [
      "hero.contractor_left",
      "hero.trust_first_hero",
      "hero.conversion_stack",
      "hero.coastal_service",
      "cta.call_now",
      "cta.request_quote",
      "services.icon_grid",
    ],
    layoutInstructions: ["rating summary", "2–3 featured reviews", "link out optional"],
    conversionStrength: 0.85,
    visualWeight: 0.5,
  },
  {
    id: "trust.project_highlight",
    category: "trust",
    name: "Project Highlight",
    industryAffinity: ["landscaping", "contractor", "portfolio", "real_estate"],
    brandAffinity: ["premium", "editorial", "handcrafted", "trustworthy"],
    tone: ["premium", "handcrafted", "editorial"],
    purpose: ["show_work", "build_trust"],
    requiredAssets: ["project_photos"],
    requiredContent: ["testimonials"],
    strengths: ["Story + proof", "Elevates craft"],
    avoidWhen: ["no_project_photos"],
    compatiblePatterns: [
      "hero.cinematic_full_width",
      "hero.editorial_split",
      "hero.asymmetric_craft",
      "gallery.featured_project",
      "gallery.case_studies",
      "cta.project_inquiry",
      "services.image_focus",
    ],
    layoutInstructions: ["one featured project", "outcome statement", "photo dominant"],
    conversionStrength: 0.74,
    visualWeight: 0.65,
  },
  {
    id: "trust.before_after",
    category: "trust",
    name: "Before / After",
    industryAffinity: ["landscaping", "contractor", "salon", "local_service"],
    brandAffinity: ["trustworthy", "handcrafted", "approachable"],
    tone: ["trustworthy", "handcrafted"],
    purpose: ["show_work", "build_trust"],
    requiredAssets: ["before_after"],
    requiredContent: ["headline"],
    strengths: ["Irrefutable transformation", "Scroll-stopping"],
    avoidWhen: ["no_before_after_assets"],
    compatiblePatterns: [
      "hero.before_after_hero",
      "hero.cinematic_full_width",
      "gallery.before_after",
      "cta.estimate",
      "cta.request_quote",
      "services.process_cards",
    ],
    layoutInstructions: ["paired images", "short caption", "CTA nearby"],
    conversionStrength: 0.9,
    visualWeight: 0.7,
  },
  {
    id: "trust.local_badges",
    category: "trust",
    name: "Local Badges",
    industryAffinity: ["local_service", "contractor", "landscaping", "retail"],
    brandAffinity: ["trustworthy", "approachable", "handcrafted"],
    tone: ["trustworthy", "approachable"],
    purpose: ["local_proof", "build_trust"],
    requiredAssets: ["logo", "none"],
    requiredContent: ["awards"],
    strengths: ["Community credibility", "Compact"],
    avoidWhen: ["no_local_affiliations"],
    compatiblePatterns: [
      "hero.coastal_service",
      "hero.local_banner",
      "hero.contractor_left",
      "cta.schedule_visit",
      "services.large_cards",
    ],
    layoutInstructions: ["badge row", "muted logos", "short affiliation labels"],
    conversionStrength: 0.7,
    visualWeight: 0.35,
  },
  {
    id: "trust.awards",
    category: "trust",
    name: "Awards",
    industryAffinity: ["luxury", "restaurant", "salon", "professional_services", "real_estate"],
    brandAffinity: ["luxury", "premium", "timeless", "editorial"],
    tone: ["luxury", "premium", "timeless"],
    purpose: ["premium_positioning", "build_trust"],
    requiredAssets: ["none"],
    requiredContent: ["awards"],
    strengths: ["Status signaling", "Pairs with luxury heroes"],
    avoidWhen: ["no_awards"],
    compatiblePatterns: [
      "hero.luxury_center",
      "hero.premium_minimal",
      "hero.restaurant_atmosphere",
      "cta.luxury_contact",
      "cta.reserve_table",
      "services.premium_tiles",
    ],
    layoutInstructions: ["elegant award marks", "year + title", "sparse layout"],
    conversionStrength: 0.62,
    visualWeight: 0.4,
  },
  {
    id: "trust.guarantee",
    category: "trust",
    name: "Guarantee",
    industryAffinity: ["contractor", "landscaping", "local_service", "retail"],
    brandAffinity: ["trustworthy", "approachable", "modern"],
    tone: ["trustworthy", "approachable"],
    purpose: ["build_trust", "drive_conversion"],
    requiredAssets: ["none"],
    requiredContent: ["headline"],
    strengths: ["Risk reversal", "Boosts quote requests"],
    avoidWhen: ["cannot_support_guarantee"],
    compatiblePatterns: [
      "hero.contractor_left",
      "hero.conversion_stack",
      "hero.process_hero",
      "cta.request_quote",
      "cta.estimate",
      "services.process_cards",
    ],
    layoutInstructions: ["clear guarantee statement", "short conditions", "icon optional"],
    conversionStrength: 0.88,
    visualWeight: 0.45,
  },
  {
    id: "trust.certifications",
    category: "trust",
    name: "Certifications",
    industryAffinity: ["professional_services", "contractor", "local_service", "general"],
    brandAffinity: ["trustworthy", "timeless", "modern", "minimalist"],
    tone: ["trustworthy", "timeless"],
    purpose: ["build_trust"],
    requiredAssets: ["none"],
    requiredContent: ["awards"],
    strengths: ["Competence proof", "Good for regulated trades"],
    avoidWhen: ["no_certifications"],
    compatiblePatterns: [
      "hero.process_hero",
      "hero.soft_gradient_service",
      "cta.book_consultation",
      "services.timeline",
      "services.icon_grid",
    ],
    layoutInstructions: ["cert logo strip", "credential names", "low visual noise"],
    conversionStrength: 0.72,
    visualWeight: 0.38,
  },
  {
    id: "trust.partner_logos",
    category: "trust",
    name: "Partner Logos",
    industryAffinity: ["professional_services", "contractor", "retail", "general"],
    brandAffinity: ["modern", "trustworthy", "minimalist", "premium"],
    tone: ["modern", "trustworthy", "minimalist"],
    purpose: ["build_trust"],
    requiredAssets: ["logo"],
    requiredContent: [],
    strengths: ["Borrowed authority", "Lightweight"],
    avoidWhen: ["no_partners"],
    compatiblePatterns: [
      "hero.premium_minimal",
      "hero.local_banner",
      "cta.minimal_cta",
      "services.feature_strips",
    ],
    layoutInstructions: ["grayscale logos", "even spacing", "no hard sell"],
    conversionStrength: 0.55,
    visualWeight: 0.3,
  },
  {
    id: "trust.team_trust",
    category: "trust",
    name: "Team Trust",
    industryAffinity: ["professional_services", "salon", "portfolio", "general"],
    brandAffinity: ["approachable", "editorial", "handcrafted", "trustworthy"],
    tone: ["approachable", "editorial", "handcrafted"],
    purpose: ["build_trust"],
    requiredAssets: ["team_photo"],
    requiredContent: ["testimonials"],
    strengths: ["Humanizes the brand", "Good for relationship businesses"],
    avoidWhen: ["no_team_photos"],
    compatiblePatterns: [
      "hero.editorial_split",
      "hero.bold_statement",
      "cta.book_consultation",
      "services.alternating",
      "gallery.alternating",
    ],
    layoutInstructions: ["team portraits", "short bios or roles", "warm photography"],
    conversionStrength: 0.68,
    visualWeight: 0.58,
  },
  {
    id: "trust.stats_bar",
    category: "trust",
    name: "Stats Bar",
    industryAffinity: ["contractor", "landscaping", "professional_services", "general"],
    brandAffinity: ["modern", "trustworthy", "premium", "timeless"],
    tone: ["modern", "trustworthy", "premium"],
    purpose: ["build_trust", "local_proof"],
    requiredAssets: ["none"],
    requiredContent: ["headline"],
    strengths: ["Quick credibility", "Bridges hero to services"],
    avoidWhen: ["no_credible_stats"],
    compatiblePatterns: [
      "hero.contractor_left",
      "hero.cinematic_full_width",
      "hero.dual_cta_hero",
      "services.large_cards",
      "cta.request_quote",
    ],
    layoutInstructions: ["3–4 metrics", "years/projects/rating", "compact band"],
    conversionStrength: 0.7,
    visualWeight: 0.42,
  },
  {
    id: "trust.press_mentions",
    category: "trust",
    name: "Press Mentions",
    industryAffinity: ["luxury", "restaurant", "salon", "portfolio", "retail"],
    brandAffinity: ["editorial", "luxury", "premium", "timeless"],
    tone: ["editorial", "luxury", "premium"],
    purpose: ["premium_positioning", "build_trust"],
    requiredAssets: ["none"],
    requiredContent: ["awards"],
    strengths: ["Editorial authority", "Luxury adjacency"],
    avoidWhen: ["no_press"],
    compatiblePatterns: [
      "hero.luxury_center",
      "hero.editorial_split",
      "hero.restaurant_atmosphere",
      "cta.luxury_contact",
      "gallery.case_studies",
    ],
    layoutInstructions: ["publication marks", "short pull quote optional"],
    conversionStrength: 0.58,
    visualWeight: 0.36,
  },
];
